services:
  mariadb:
    image: mariadb:10.6.4-focal
    volumes:
      - "/home/$USER/data/mariadb:/var/lib/mysql"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?required}
      - MYSQL_USER=${MYSQL_USER:?required}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?required}
      - MYSQL_DATABASE=${MYSQL_DATABASE:?required}
  wordpress:
    image: wordpress:php8.2-fpm-alpine
    depends_on:
      - mariadb
    volumes:
      - "/home/$USER/data/wordpress:/var/www/html"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${MYSQL_USER:?required}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD:?required}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE:?required}
  nginx:
    image: nginx:1.24.0-alpine3.17
    depends_on:
      - wordpress
    volumes:
      - "/home/$USER/data/wordpress:/var/www/html"
      - ./requirements/nginx/conf/config.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    restart: always
