services:
  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
    volumes:
      - ./requirements/mariadb/conf/config.conf:/etc/my.cnf
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?required}
      - MYSQL_USER=${MYSQL_USER:?required}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?required}
      - MYSQL_DATABASE=${MYSQL_DATABASE:?required}
  wordpress:
    image: wordpress
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
      - ./requirements/wordpress/conf/config.conf:/etc/php/php-fpm.d/www.conf:ro
    networks:
      - inception
    restart: always
    environment:
      - DB_HOST=mariadb
      - DB_USER=${MYSQL_USER:?required}
      - DB_PASSWORD=${MYSQL_PASSWORD:?required}
      - DB_NAME=${MYSQL_DATABASE:?required}
      - WORDPRESS_URL=${DOMAIN_NAME:?required}
      - WORDPRESS_SITE_TITLE=${WORDPRESS_SITE_TITLE:?required}
      - WORDPRESS_ADMIN=${WORDPRESS_ADMIN:?required}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL:?required}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD:?required}
      - WORDPRESS_EDITOR=${WORDPRESS_EDITOR:?required}
      - WORDPRESS_EDITOR_EMAIL=${WORDPRESS_EDITOR_EMAIL:?required}
      - WORDPRESS_EDITOR_PASSWORD=${WORDPRESS_EDITOR_PASSWORD:?required}
  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
    depends_on:
      - wordpress
      - portfolio
    volumes:
      - wordpress:/var/www/html:ro
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./requirements/nginx/conf/config.conf:/etc/nginx/conf.d/default.conf:ro
      - ./requirements/nginx/conf/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./requirements/nginx/conf/self-signed.conf:/etc/nginx/snippets/self-signed.conf:ro
      - ./requirements/nginx/conf/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf:ro
    networks:
      - inception
    ports:
      - 443:443
    restart: always
  portfolio:
    image: portfolio
    build:
      context: ./requirements/bonus/nginx
    volumes:
      - ./requirements/bonus/nginx/html:/var/www/html:ro
      - ./requirements/bonus/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./requirements/bonus/nginx/conf/config.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - inception
    restart: always
volumes:
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/home/$USER/data/mariadb"
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/home/$USER/data/wordpress"
networks:
  inception:
    name: inception
